//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorTCP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientID
    {
        public int UserClientID { get; set; }
        public int UserID { get; set; }
        public int ClientID1 { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
