//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorTCP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientIDs = new HashSet<ClientID>();
        }
    
        public int ClientsID { get; set; }
        public string ClientId { get; set; }
        public string IP_Address { get; set; }
        public string MachineName { get; set; }
        public string LoggedOnUserName { get; set; }
    
        public virtual ICollection<ClientID> ClientIDs { get; set; }
    }
}
