//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorTCP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Jurisdictions = new HashSet<Jurisdiction>();
            this.Users = new HashSet<User>();
        }
    
        public int CountryId { get; set; }
        public string CountryNameEnglish { get; set; }
        public string CountryNameLocal { get; set; }
        public int CountryTimeZone { get; set; }
        public int StatesId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Jurisdiction> Jurisdictions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
