//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorTCP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public byte[] CreatedOnDate { get; set; }
        public string NewsSummary { get; set; }
        public string NewsContent { get; set; }
        public string NewsTitle { get; set; }
        public string NewsSource { get; set; }
        public string Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
