//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorTCP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestrictionType
    {
        public RestrictionType()
        {
            this.Restricteds = new HashSet<Restricted>();
        }
    
        public int RestrictionId { get; set; }
        public string Restriction_Reason { get; set; }
    
        public virtual ICollection<Restricted> Restricteds { get; set; }
    }
}
