//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentObject
    {
        public ContentObject()
        {
            this.ContentObjectsSourceURLS = new HashSet<ContentObjectsSourceURL>();
        }
    
        public int ContentObjectId { get; set; }
        public string ContentPath { get; set; }
        public Nullable<int> ARCId { get; set; }
        public string ContentObjectExtension { get; set; }
        public string ContentObjectHash { get; set; }
    
        public virtual ARC ARC { get; set; }
        public virtual ICollection<ContentObjectsSourceURL> ContentObjectsSourceURLS { get; set; }
    }
}
