//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurisdiction
    {
        public Jurisdiction()
        {
            this.Alloweds = new HashSet<Allowed>();
            this.Criminals = new HashSet<Criminal>();
            this.Restricteds = new HashSet<Restricted>();
            this.Users = new HashSet<User>();
        }
    
        public int JurisdictionId { get; set; }
        public string JurisdictionName { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int LanguageId { get; set; }
    
        public virtual ICollection<Allowed> Alloweds { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Criminal> Criminals { get; set; }
        public virtual State State { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Restricted> Restricteds { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
