//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restricted
    {
        public Restricted()
        {
            this.ARCs = new HashSet<ARC>();
        }
    
        public int RId { get; set; }
        public int UId { get; set; }
        public int RestrictedToId { get; set; }
        public int JurisdictionId { get; set; }
    
        public virtual ICollection<ARC> ARCs { get; set; }
        public virtual Jurisdiction Jurisdiction { get; set; }
        public virtual RestrictionType RestrictionType { get; set; }
        public virtual User User { get; set; }
    }
}
