//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlSource
    {
        public int UrlSourcesId { get; set; }
        public int URLId { get; set; }
        public int URLSourceId { get; set; }
    
        public virtual URL URL { get; set; }
        public virtual URL URL1 { get; set; }
    }
}
